### ISSUE TITLE
Error Data length does not match: 1 2

### ISSUE THREAD

**Issue by igrangel** [i40-Tools/SemCPS#10]
For the following testbeds:

1. Single-Heterogeneity/M1/M1.1/Testbeds-0/-1/-2/ as well as for the Multi-Heterogeneity

Stack trace
```
java.lang.IllegalArgumentException: Data length does not match: 1 2 at edu.umd.cs.psl.database.rdbms.RDBMSDataLoader$RDBMSTableInserter.insertInternal(RDBMSDataLoader.java:161)
at edu.umd.cs.psl.database.rdbms.RDBMSDataLoader$RDBMSTableInserter.insert(RDBMSDataLoader.java:143) at edu.umd.cs.psl.database.rdbms.RDBMSDataLoader$RDBMSInserter.insert(RDBMSDataLoader.java:83)
at edu.umd.cs.psl.ui.loading.InserterUtils$1.create(InserterUtils.java:50)
at edu.umd.cs.psl.ui.loading.InserterUtils$1.create(InserterUtils.java:45)
at edu.umd.cs.psl.ui.data.file.util.LoadDelimitedData.loadTabData(LoadDelimitedData.java:52)
at edu.umd.cs.psl.ui.loading.InserterUtils.loadDelimitedData(InserterUtils.java:45)
at edu.umd.cs.psl.ui.loading.InserterUtils.loadDelimitedData(InserterUtils.java:63)
at edu.umd.cs.psl.ui.loading.InserterUtils$loadDelimitedData.call(Unknown Source)
at pslApproach.DocumentAligment.setUpData(DocumentAlignment.groovy:398)
at pslApproach.DocumentAligment.run(DocumentAlignment.groovy:65)
at pslApproach.DocumentAligment$run$0.call(Unknown Source)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
at pslApproach.DocumentAligment.execute(DocumentAlignment.groovy:73)
at pslApproach.DocumentAligment$execute.call(Unknown Source)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
at pslApproach.DocumentAligment.main(DocumentAlignment.groovy:56)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1207)
at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:807)
at pslApproach.DocumentAligment.invokeMethod(DocumentAlignment.groovy)
at org.codehaus.groovy.runtime.InvokerHelper$2.run(InvokerHelper.java:433)
at groovy.lang.GroovyShell.evaluate(GroovyShell.java:570)
at groovy.lang.GroovyShell.evaluate(GroovyShell.java:617)
at groovy.lang.Script.evaluate(Script.java:219)
at main.AlligatorMain.executePSLAproach(AlligatorMain.java:100)
at main.AlligatorMain.main(AlligatorMain.java:38)
```

**Comment by omarrana** [comment]
fixed
